
import { Inter } from 'next/font/google'
import './globals.css'
import TopNavbar from './component/TopNavbar/TopNavbar'
import Navbar from './component/Navbar/Navbar'

import Footer from './component/Footer/Footer'
import BottomNav from './component/BottomNav/BottomNav'


import ReduxProvider from '@/redux/ReduxProvider/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Exclusive',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className + " overflow-x-hidden"}>
        <ReduxProvider>
          <TopNavbar></TopNavbar>
          <Navbar></Navbar>
          <hr />

          {children}

          <Footer></Footer>
          <BottomNav></BottomNav>
        </ReduxProvider>

      </body>

    </html>
  )
}
